{% set name = "iprPy" %}
{% set version = "0.11.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8cf793a596615eae2157cc2562d5c5c198a464bfa032dad9731dce242fb1e44c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - iprPy = iprPy.command_line:command_line

requirements:
  build:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pip
    - datamodeldict
    - numpy >=1.15
    - matplotlib-base
    - scipy
    - pandas
    - atomman =1.4.5
    - requests
    - bokeh

test:
  imports:
    - iprPy
  commands:
    - pip check

about:
  home: https://www.ctcms.nist.gov/potentials/iprPy/
  license: NIST-PD
  license_file: LICENSE.TXT
  summary: NIST Interatomic Potential Repository property calculation tools

  description: |
    The iprPy framework is a collection of tools and resources supporting the
    design of scientific calculations that are open source with minimum
    barriers for usage, have transparent methodologies supporting knowledge
    transfer and education, produce results that are both human and machine
    readable, allow investigations into method and parameter sensitivity, and
    can be integrated into workflows. The framework was originally created to
    support the NIST Interatomic Potential Repository by evaluating basic
    materials properties across multiple classical interatomic potentials.
    Because of this, many of the included calculations and tools are designed
    towards molecular dynamics simulations.
  doc_url: https://www.ctcms.nist.gov/potentials/iprPy/
  dev_url: https://github.com/usnistgov/iprPy

extra:
  recipe-maintainers:
    - jan-janssen
    - lmhale99
